# Generated by Django 5.0.4 on 2024-05-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('terrenos', models.CharField(max_length=500, verbose_name='Terrenos')),
            ],
            options={
                'verbose_name': 'Web',
                'verbose_name_plural': 'Webs',
            },
        ),
    ]
