# Generated by Django 5.0.4 on 2024-05-13 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(choices=[('activo', 'Activo'), ('no activo', 'No Activo')], default='activo', max_length=20)),
                ('documento', models.IntegerField(max_length=9)),
                ('nombre', models.CharField(max_length=200)),
                ('ap_paterno', models.CharField(max_length=50)),
                ('ap_Materno', models.CharField(max_length=50)),
                ('celular', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inversionista', 'Inversionista'), ('socio', 'Socio')], default='inversionista', max_length=20)),
                ('cantidad_invertida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_ganancia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proyectos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socio')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_invertida', models.FloatField()),
                ('monto', models.IntegerField()),
                ('saldo', models.IntegerField()),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('inversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.inversion')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
