# Generated by Django 5.0.4 on 2024-05-13 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='datosusuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=200, verbose_name='Identificacion')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre, Apellido')),
                ('imagen', models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='Imagen')),
                ('imagenlogo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen')),
                ('area', models.CharField(blank=True, max_length=200, null=True, verbose_name='Area')),
                ('cargo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cargo')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('NO ACTIVO', 'No')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('Telefono', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefono')),
                ('Comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('tutorial', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=20, null=True, verbose_name='Tutorial')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos', verbose_name='Proyecto que sigue')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dato de usuario',
                'verbose_name_plural': 'Datos de los usuarios',
            },
        ),
        migrations.CreateModel(
            name='ActividadesUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30, verbose_name='Categoria')),
                ('accion', models.CharField(max_length=50, verbose_name='Acción')),
                ('momento', models.DateTimeField(verbose_name='Fecha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.datosusuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
